require 'rubygems'
require 'rake'
require 'rake/testtask'

DIR = File.dirname( __FILE__ )

task :default => [ "test:mysql" ]

task :boot do 
    require File.join( DIR, 'tests', 'boot' )  
end

ADAPTERS = %w( mysql postgresql sqlite )

namespace :db do

  namespace :test do
    ADAPTERS.each do |adapter|
      desc "builds test database for #{adapter}"
      task "prepare_#{adapter}" do |t|
        ENV['ARE_DB'] = adapter
        require File.join( DIR, 'tests', 'boot' )
        require File.join( DIR, 'db', 'migrate', 'generic_schema' )        
        db_schema = File.join( DIR, 'db', 'migrate', "#{adapter}_schema" )
        require db_schema if File.exists?( db_schema )
      end
    end
  end

end

namespace :test do
  
  ADAPTERS.each do |adapter|
    desc "test base extensions for #{adapter}"
    task adapter do |t|
      ENV['ARE_DB'] = adapter
      Dir[ File.join( DIR, 'tests', 'test_*.rb' ) ].each{ |f| require f }
      Dir[ File.join( DIR, 'tests', adapter.to_s, 'test_*.rb' ) ].each{ |f| require f }
    end
  end
  
  namespace :activerecord do

    ADAPTERS.each do |adapter|
      desc "runs ActiveRecord unit tests for #{adapter} with ActiveRecord::Extensions"
      task adapter.to_sym do |t|
        activerecord_dir = ARGV[1]
        if activerecord_dir.nil? or ! File.directory?( activerecord_dir )
          STDERR.puts "ERROR: Pass in the path to ActiveRecord. Eg: /home/joe/rails_trunk/activerecord"
          exit
        end
        
        old_dir, old_env = Dir.pwd, ENV['RUBYOPT']
        Dir.chdir( activerecord_dir )
        ENV['RUBYOPT'] = "-r#{File.join(old_dir,'init.rb')}"

        load "Rakefile"
        Rake::Task[ "test_#{adapter}" ].invoke
        Dir.chdir( old_dir )
        ENV['RUBYOPT'] = old_env
        
      end      
  
    end  
          
  end    
  
end
