require 'rubygems'
require 'rake'
require 'rake/testtask'

DIR = File.dirname( __FILE__ )

task :default => [ "test:mysql" ]

task :boot do 
    require File.join( DIR, 'tests', 'boot' )  
end

namespace :test do
  
  desc "test base extensions"
  task :mysql do |t|
    Dir[ File.join( DIR, 'tests', 'test_*.rb' ) ].each{ |f| require f }
  end
  
  namespace :activerecord do

    desc "runs ActiveRecord unit tests for MySQL with loading "
    task :mysql => [ :boot ] do |t|
      activerecord_dir = ARGV[1]
      if activerecord_dir.nil? or ! File.directory?( activerecord_dir )
        STDERR.puts "ERROR: Pass in the path to ActiveRecord. Eg: /home/joe/rails_trunk/activerecord"
        exit
      end
      
      old_dir, old_env = Dir.pwd, ENV['RUBYOPT']
      Dir.chdir( activerecord_dir )
      ENV['RUBYOPT'] = "-r#{File.join(old_dir,'init.rb')}"
      load "Rakefile"
      Rake::Task[ 'test_mysql' ].invoke
      Dir.chdir( old_dir )
      ENV['RUBYOPT'] = old_env
    end
    
  end
    
end
